name: vad_example
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.0+1
  audioplayers: ^6.5.0
  vad:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  import_sorter: ^4.6.0

dependency_overrides:
  record:
    git:
      url: https://github.com/keyur2maru/record.git
      ref: master
      path: record
  record_macos:
    git:
      url: https://github.com/keyur2maru/record.git
      ref: master
      path: record_macos

flutter:
  uses-material-design: true
  assets:
    - assets/